Assignment # 3
========================================================

Download the file
```{r}
fileUrl <- "https://d396qusza40orc.cloudfront.net/rprog%2Fdata%2FProgAssignment3-data.zip"

if (!file.exists("Assignment3-data.zip")) {
    download.file(fileUrl, destfile = "Assignment3-data.zip", method = "wget")
}
```

Unzip the file

```{r}
if (!file.exists("Assignment3-data")) {
    unzip("Assignment3-data.zip", overwrite = TRUE)
}
```


```{r}
getwd()
```


1 Plot the 30-day mortality rates for heart attack
```{r}
outcome <- read.csv("outcome-of-care-measures.csv", colClasses = "character")
head(outcome)
```

Number of columns 
```{r}
ncol(outcome)
```


```{r}
names(outcome)
```

To make a simple histogram of the 30-day death rates from heart attack (column 11 in the outcome dataset), run
```{r}
names(outcome)[11]
outcome[, 11] <- as.numeric(outcome[, 11])
## You may get a warning about NAs being introduced; that is okay
```

```{r fig.width=7, fig.height=6}
hist(outcome[, 11])
```



```{r}

```

